package com.seeyon.apps.babi.util;

import com.seeyon.apps.babi.pojo.SapReadYFK;

public class GetXmlString {
	
	public static String YFKXmlToString(SapReadYFK YFKObj)
	{
		StringBuffer str = new StringBuffer("<?xml version=\"1.0\" encoding=\"UTF-8\"?><formExport version=\"2.0\">");
		str.append("<summary id=\"-1921791307175408875\" name=\"formmain_2492\" />");
		str.append("<definitions />");
		str.append("<values>");
		str.append("<column name=\"日期\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"流程编号\">");
		str.append("<value>"+YFKObj.getFiowid()+"</value>");
		str.append("</column>");
		str.append("<column name=\"合计本次预付款金额大写\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"供应商代码\">");
		str.append("<value>"+YFKObj.getSupplier_number()+"</value>");
		str.append("</column>");
		str.append("<column name=\"供应商名称\">");
		str.append("<value>"+YFKObj.getSupplier_name()+"</value>");
		str.append("</column>");
		str.append("<column name=\"填报部门\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"申请人\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"开户银行\">");
		str.append("<value>"+YFKObj.getBank_name()+"</value>");
		str.append("</column>");
		str.append("<column name=\"银行账号\">");
		str.append("<value>"+YFKObj.getBank_number()+"</value>");
		str.append("</column>");
		str.append("<column name=\"预付款说明\">");
		str.append("<value>"+YFKObj.getExplain()+"</value>");
		str.append("</column>");
		str.append("<column name=\"凭证类型\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"货币码\">");
		str.append("<value>"+YFKObj.getCurrency()+"</value>");
		str.append("</column>");
		str.append("<column name=\"供应商类别\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"合计本次预付款金额小写\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"预计结账日期\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"附件数\">");
		str.append("<value>"+YFKObj.getAccessory_amount()+"</value>");
		str.append("</column>");
		str.append("<column name=\"累计付款\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"本次付款金额\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"付款方式\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"开户银行公司带出\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"银行账号银行带出\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"科室负责人\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"采购部负责人\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"会计经理\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"财务总监\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"总经理审批\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"董事长审批\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"是否付款\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"付款时间\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"付款金额\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"币种\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"原币金额\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"汇率\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"本位币金额\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"原因代码\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"行号\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"记账代码\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"会计科目代码\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"行号1\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"记账代码1\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"记账方向1\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"特别总账标识1\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"会计姓名\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"处理日期\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"公司名称\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"公司代码\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"创建人1\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"创建部门1\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"创建人员机构\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"申请人员机构\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"表单名称-隐藏字段\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"创建员工编号-隐藏\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"申请人员编号-隐藏\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"出纳姓名-隐藏\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"出纳人编号-隐藏\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"会计编号-隐藏\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("<column name=\"出纳操作日期-隐藏\">");
		str.append("<value></value>");
		str.append("</column>");
		str.append("</values>");
		str.append("<subForms>");
		str.append("<subForm>");
		str.append("<definitions>");
		str.append("<column id=\"field0058\" type=\"4\" name=\"明细序号\" length=\"255\" />");
		str.append("<column id=\"field0059\" type=\"0\" name=\"采购订单\" length=\"255\" />");
		str.append("<column id=\"field0060\" type=\"0\" name=\"采购合同\" length=\"255\" />");
		str.append("<column id=\"field0061\" type=\"4\" name=\"合同金额\" length=\"255\" />");
		str.append("<column id=\"field0062\" type=\"4\" name=\"比例\" length=\"255\" />");
		str.append("<column id=\"field0063\" type=\"4\" name=\"预付金额\" length=\"255\" />");
		str.append("</definitions>");
		str.append("<values>");
		
		for (com.seeyon.apps.babi.pojo.YFKObj yfk : YFKObj.getYFKlist()) {
			str.append("<row>");
			str.append("<column name=\"明细序号\">");
			str.append("<value></value>");
			str.append("</column>");
			str.append("<column name=\"采购订单\">");
			str.append("<value>"+yfk.getProcurement_dingdan_number()+"</value>");
			str.append("</column>");
			str.append("<column name=\"采购合同\">");
			str.append("<value></value>");
			str.append("</column>");
			str.append("<column name=\"合同金额\">");
			str.append("<value></value>");
			str.append("</column>");
			str.append("<column name=\"比例\">");
			str.append("<value></value>");
			str.append("</column>");
			str.append("<column name=\"预付金额\">");
			str.append("<value>"+yfk.getPrepay_money()+"</value>");
			str.append("</column>");
			str.append("</row>");
		}
		str.append("</values>");
		str.append("</subForm>");
		str.append("</subForms>");
		str.append("</formExport>");
		
		return str.toString();
	}
}
